swagger: '2.0'
info:
   $ref: ./info/index.yaml
# host: api.openbanking.xyz
# basePath: /open-banking.xyz
# schemes: https
#definitions:
# let's DRY everything in definitions
#  $ref: ./definitions/index.yaml
paths:
  $ref: ./paths/index.yaml
securityDefinitions:
  OAuth2Security:
    type: oauth2
    flow: password
    tokenUrl: '/token'
    scopes:
      # payments:manage: top level generic scope to setup, submit, cancel and get status of a  payment
      payments:setup: ability to create/setup a payment, not to be confused with submit
      payments:submit: submit a payment
      payments:cancel: cancel a future dated/recurring payment
      payments:status: allows to retrieve status of a payment
      # payments:recurring_manage: top level generic scope to setup, submit and cancel a payment
      payments:recurring_setup: ability to create/setup a payment, not to be confused with submit
      payments:recurring_submit: submit a future dated/recurring payment
      payments:recurring_cancel: cancel a future dated/recurring payment
      payments:recurring_status: allows to retrieve status of a future dated/recurring payment
      # payments:complex_manage: top level generic scope to setup, submit and cancel a payment
      payments:complex_setup: ability to create/setup a complex payment, not to be confused with submit
      payments:complex_submit: submit a complex payment
      payments:complex_cancel: cancel a future dated/recurring complex payment
      payments:complex_status: allows to retrieve status of a complex payment
