swagger: '2.0'
info:
   $ref: ./info/index.yaml
# host: api.openbanking.xyz
# basePath: /open-banking.xyz
# schemes: https
#definitions:
# let's DRY everything in definitions
#  $ref: ./definitions/index.yaml
paths:
  $ref: ./paths/index.yaml
# parameters:
#   $ref: ./parameters/index.yaml
