swagger: '2.0'
info:
   $ref: ./info/index.yaml
# host: api.openbanking.xyz
basePath: /open-banking
schemes:
  - https
produces:
  - $ref: ./definitions/mime_type.yaml
# definitions:
#  $ref: ./definitions/index.yaml
paths:
 $ref: ./paths/index.yaml
securityDefinitions:
  $ref: ./security/index.yaml
#tags section, to organise endpoints
tags:
 - name: Simple Payment
   description: Simple Payments endpoints
 # - name: Complex Payment
 #   description: Complex Payments endpoints
#common responses (errors)

responses:
  $ref: ./responses/index.yaml
