type: oauth2
flow: application
tokenUrl: 'https://authserver.example/token'
scopes:
  tpp_client_credential: TPP Client Credential Scope
description: TPP client credential authorisation flow with the ASPSP
