type: oauth2
flow: application
host: 'https://authserver.example/'
tokenUrl: '/token'
scopes:
  tpp_client_credential: TPP Client Credential Scope
description: TPP client credential authorisation flow with the ASPSP
